/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    ", SPD:": ", 速度:",
    "Defeated:": "击败:",
    "HP:": "生命:",
    "DMG:": "伤害:",
    "Main": "主界面",
    "Level": "等级",
    "Stats": "属性",
    "Options": "选项",
    "Trophies": "奖杯",
    "XP:": "经验:",
    "Up Quark": "上夸克",
    "May be a weakling, but don't x-pect much until later on...": "可能是个弱者，但不要抱太大希望，直到以后……",
    "Enemies": "敌人",
    "Abilities:": "能力：",
    "Heal;": "治疗；",
    "With its quark bretheren, they have discovered a pattern going up, up, down, down. Further research needed.": "有了它的夸克兄弟，他们发现了一种上升、上升、下降、下降的模式。 需要进一步研究。",
    "Turns out love is at an elementary level after all. Not that you'd want to fall in love with this one...": "原来爱情终究是初级水平的。 并不是说你想爱上这个......",
    "Stun;": "击晕；",
    "Weaken;": "虚弱；",
    "Technically named the \"S-Quark\", this little particle rotates 90 degrees sometimes for literally no reason.": "技术上称为“S-夸克”，这个小粒子有时会无缘无故地旋转 90 度。",
    "Quantum tunneling research shows that about 6.2831853071% of Tau particles came from the Death Star.": "量子隧穿研究表明，大约 6.2831853071% 的 Tau 粒子来自死星。",
    "The counterpart of the top quark, but isn't its antiparticle. Known to be the most beautiful quark (citation needed).": "顶夸克的对应物，但不是它的反粒子。 已知是最美丽的夸克（需要引用）。",
    "Feels ostracized from the quark community, so it has become a true pessimist.": "感觉自己被夸克界排斥了，所以变成了真正的悲观主义者。",
    "Not to be confused with up quark, is the blunt \"older sibling\" of the quark family.": "不要与上夸克混淆，它是夸克家族直截了当的“大哥”。",
    "Agile;": "敏捷;",
    "Mutator;": "突变体；",
    "It seems to be gazing directly into your soul. Trouble is, particles don't have eyes.": "仿佛直视你的灵魂。 问题是，粒子没有眼睛。",
    "Shield;": "护盾；",
    "Counter;": "反击;",
    "A very tiny particle, that has managed to pull three larger ones into its orbit. Is Greek in origin.": "一个非常小的粒子，成功地将三个较大的粒子拉入其轨道。 起源于希腊语。",
    "Enemy has a 40% chance to counterattack the player when attacked.": "敌人受到攻击时有 40% 的几率反击玩家。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "lens": "lens",
    "chevron_left": "chevron_left",
    "chevron_right": "chevron_right",
    "→": "→",
    "←": "←",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Up Quark": "上夸克",
    "Selected: ": "已选择：",
    "Offline: ": "离线：",
    "Charm Quark": "魅力夸克",
    "Down Quark": "下夸克",
    "Bottom Quark": "底夸克",
    "Electron": "电子",
    "Strange Quark": "奇异夸克",
    "Top Quark": "顶夸克",
    "Muon": "介子",
    "Tau": "Tau",
    " Neutrino": " 中微子",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Stage": "阶段",
    "Neutrino": "中微子",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^ \[([\d\.,]+)\]$/,
    /^ \[Rk ([\d\.,]+)\]$/,
    /^([\d\.,]+) \/ ∞$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Effect: Heals (.+) HP per kill$/, '效果：每次击杀治疗 $1 生命值'],
    [/^Effect: Heals (.+) HP per second$/, '效果：每秒治疗 $1 生命值'],
    [/^Effect: (.+) Base DMG$/, '效果：$1 基础伤害'],
    [/^Effect: (.+) DMG$/, '效果：$1 伤害'],
    [/^Effect: (.+) HP$/, '效果：$1 生命'],
    [/^Effect: (.+) SPD$/, '效果：$1 速度'],
    [/^Effect: (.+) Critical Hit Chance \(5x DMG\)$/, '效果：$1 暴击率（5x 伤害）'],
    [/^Effect: Divides Enemy DMG by (.+)$/, '效果：除以敌人伤害 $1'],
    [/^Effect: Divides Enemy SPD by (.+)$/, '效果：除以敌人速度 $1'],
    [/^Effect: Divides Enemy healing by (.+)$/, '效果：除以敌人治疗 $1'],
    [/^Effect: Divides enemy healing by (.+)$/, '效果：除以敌人治疗 $1'],
    [/^Effect: Enemy Stun, Heal, \& Agile abilities have a (.+) chance to fail$/, '效果：敌人的眩晕、治疗和敏捷技能有 $1 的几率失败'],
    [/^Auto Cost: (.+) Tau Neutrino Trophies$/, '自动成本：$1 Tau中微子奖杯'],
    [/^Auto Cost: (.+) Electron Neutrino Trophies$/, '自动成本：$1 电子中微子奖杯'],
    [/^Auto Cost: (.+) Muon Neutrino Trophies$/, '自动成本：$1 介子中微子奖杯'],
    [/^Auto Cost: (.+) Muon Trophies$/, '自动成本：$1 介子奖杯'],
    [/^Auto Cost: (.+) Tau Trophies$/, '自动成本：$1 Tau奖杯'],
    [/^Auto Cost: (.+) Electron Trophies$/, '自动成本：$1 电子奖杯'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);